version: '3.1'

services:
    db:
      image: surrealdb/surrealdb:latest
      container_name: rustbb_surrealdb
      command:
        - start
        - --log=trace
        - --user=${DB_USER}
        - --pass=${DB_PASS}
        - file:/var/lib/surrealdb/data/mydatabase.db 
      ports:
        - ${DB_PORT}:8000
      volumes:
        - rustbb:/var/lib/surrealdb/data
      env_file:
        - .env

volumes:
  rustbb: