version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: rustbb_db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - rustbb_db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  rustbb_db: