CREATE TABLE main_forum (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX main_forum_unique ON main_forum ((true));


CREATE TABLE user_group (
	id VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
	user_title VARCHAR(255) NOT NULL UNIQUE,
	description TEXT
);

CREATE TABLE permission (
	id VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
	label VARCHAR(255) NOT NULL
);

CREATE TABLE user_group_on_permission(
	id SERIAL PRIMARY KEY,
	user_group_id VARCHAR(255) NOT NULL,
	permission_id VARCHAR(255) NOT NULL,
	value TEXT NOT NULL,
	FOREIGN KEY(user_group_id) REFERENCES user_group(id),
	FOREIGN KEY (permission_id) REFERENCES permission(id)
);

CREATE TABLE forum_user (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(320) NOT NULL UNIQUE,
	avatar_url VARCHAR(255),
	user_group_id VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_group_id) REFERENCES user_group(id)
);

CREATE TABLE category (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	creator_id INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (creator_id) REFERENCES forum_user(id)
);

CREATE TABLE forum (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	slug VARCHAR(255) NOT NULL,
	category_id INT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE thread (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	slug VARCHAR(255) NOT NULL,
	sticky BOOLEAN NOT NULL DEFAULT FALSE,
	locked BOOLEAN NOT NULL DEFAULT FALSE,
	forum_id INT NOT NULL,
	creator_id INT NOT NULL,

	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (creator_id) REFERENCES forum_user(id),
	FOREIGN KEY (forum_id) REFERENCES forum(id)
);


CREATE TABLE thread_visit (
	thread_id INT NOT NULL,
	visit_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (thread_id) REFERENCES thread(id)
);

CREATE TABLE post(
	id SERIAL PRIMARY KEY,
    content TEXT NOT NULL,
    thread_id INT NOT NULL,
    creator_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (thread_id) REFERENCES thread(id),
    FOREIGN KEY (creator_id) REFERENCES forum_user(id)
);
